openapi: 3.0.0
info:
  title: Blog API
  description: API для работы с постами (CRUD + пагинация)
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Локальный сервер

paths:
  /posts:
    get:
      summary: Получить список постов
      parameters:
        - name: page
          in: query
          description: Номер страницы
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Количество постов на странице
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'

    post:
      summary: Создать новый пост
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostInput'
      responses:
        '201':
          description: Пост создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

  /posts/{id}:
    get:
      summary: Получить пост по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Найденный пост
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Пост не найден

    put:
      summary: Обновить пост по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostInput'
      responses:
        '200':
          description: Пост обновлен

    delete:
      summary: Удалить пост по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Пост удален

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: string
          example: "1"
        title:
          type: string
          example: "Мой первый пост"
        content:
          type: string
          example: "Содержимое поста"
        createdAt:
          type: string
          format: date-time
    
    PostInput:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
